version: "3.8"

services:
  mysql_lpa:
    image: mysql:5.7
    container_name: mysql_lpa
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: larosprojectapidb
      MYSQL_USER: laros
      MYSQL_PASSWORD: laros
    ports:
      - "3306:3306"
    volumes:
      - mysql-lpa-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - local-network-lpa

  adminer_lpa:
    image: adminer:4.8.1
    container_name: adminer_lpa
    depends_on:
      - mysql_lpa
    ports:
      - "8086:8080"
    networks:
      - local-network-lpa

volumes:
  mysql-lpa-data:

networks:
  local-network-lpa:
    driver: bridge