# --------------------------------------------------------------------------------
# DB PROPERTIES
# --------------------------------------------------------------------------------

spring.jpa.database=MYSQL
spring.datasource.url=jdbc:mysql://localhost/larosprojectapi?createDatabaseIfNotExist=true&useSSL=false
spring.datasource.username=laros
spring.datasource.password=laros

spring.jpa.show-sql=true


# --------------------------------------------------------------------------------
# OTHER PROPERTIES
# --------------------------------------------------------------------------------

spring.jackson.deserialization.fail-on-unknown-properties=true

spring.jackson.date-format=yyyy-MM-dd


# --------------------------------------------------------------------------------
# SECURITY PROPERTIES
# --------------------------------------------------------------------------------

larosproject.seguridad.enable-https=false
larosproject.origen-permitido=http://localhost:4200

#Valid accessToken time
larosproject.seguridad.access-token-validity-seconds=1800

#Valid refreshToken time
larosproject.seguridad.refresh-token-validity-seconds=86400

#Authorization. Datos de Cliente.
larosproject.seguridad.with-client-one=angular
#larosproject.seguridad.secret-client-one=@ngul@r0
larosproject.seguridad.secret-client-one=$2a$10$00YdMSjWf5tlEfa1hsoyXOVeiDdybH9coHvrHPte5xMS.tIgAf4uy
larosproject.seguridad.with-client-two=mobile
#larosproject.seguridad.secret-client-two=m0b1l30
larosproject.seguridad.secret-client-two=$2a$10$KX2bY4OY8.TtSEEMdFyYAefn62at/HKifYc6cNPvCcOcNx4Q2a7iG

#Tipo de Seguridad Activada y profile para Storage local o prod (S3)
#BasicSecurityConfig = @Profile("basic-security")
#AuthorizationServerConfig e ResourceServerConfig = @Profile("oauth-security")
spring.profiles.active=local,oauth-security
#spring.profiles.active=local,basic-security


# --------------------------------------------------------------------------------
# LOGS PROPERTIES
# --------------------------------------------------------------------------------

# Enable debug logs.
#debug=false
# Enable trace logs.
#trace=true
# nivel general
logging.level.org.springframework=INFO
# logs de web
logging.level.org.springframework.web=DEBUG
# logs de seguridad
logging.level.org.springframework.security=INFO
logging.level.org.springframework.security.access=DEBUG
logging.level.org.springframework.security.authentication=DEBUG
# logs de JPA / Hibernate
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# logs de transacciones
logging.level.org.springframework.transaction=INFO
# logs de aplicacion
logging.level.com.laros.api=DEBUG


# --------------------------------------------------------------------------------
# OTHER SERVICES PROPERTIES
# --------------------------------------------------------------------------------

# Mail. Usuario y contrase�a seteados al arrancar.
# Para que funcione en local activar: https://myaccount.google.com/lesssecureapps?pli=1
larosproject.mail.host=smtp.gmail.com
larosproject.mail.port=587
larosproject.mail.username=
larosproject.mail.password=

#AWS seteados al arrancar.
#S3. 22.30. Configurando o servi�o S3
larosproject.s3.access-key-id=
larosproject.s3.secret-access-key=
larosproject.s3.bucket=aw-larosproject-files

