package com.laros.api.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Permiso generated by hbm2java
 */
@Entity
@Table(name="permiso")
public class Permiso implements java.io.Serializable {

	@Id
//	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "codigo", unique = true, nullable = false)
	private long codigo;
	
	@Column(name = "descipcion", nullable = false, length = 50)
	private String descipcion;
	
	public Permiso() {
	}

	public Permiso(long codigo, String descipcion) {
		this.codigo = codigo;
		this.descipcion = descipcion;
	}
	
	public long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(long codigo) {
		this.codigo = codigo;
	}
	
	public String getDescipcion() {
		return this.descipcion;
	}

	public void setDescipcion(String descipcion) {
		this.descipcion = descipcion;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + (int) (codigo ^ (codigo >>> 32));
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Permiso other = (Permiso) obj;
		if (codigo != other.codigo)
			return false;
		return true;
	}

}
